### ISSUE TITLE
Support multiple spaces in release name

### ISSUE THREAD

**Issue by zivillian** [jabbera/vsts-git-release-tag#1]
Currently only the first space in the release name is replaced in [entry.ts#L36](https://github.com/jabbera/vsts-git-release-tag/blob/3d3b97dbecd47bba5ffa129f16552ce5611c0f2f/Tasks/git-tag-on-release-task/entry.ts#L36).

**Comment by jabbera** [comment]
Ha. Typescript weirdness IMO. I'll sort this on Tuesday.

**Comment by jabbera** [comment]
This is sorted as part of: https://github.com/jabbera/vsts-git-release-tag/commit/74bad69d12daf94f34cc823e531cb00458415c8d
