### ISSUE TITLE
Does it work with TFS 2015 Update 3?

### ISSUE THREAD

**Issue by ricardoserradas** [jabbera/vsts-git-release-tag#10]
I'm unable to make it work on my TFS 2015 U3 instance.

I'm receiving the following error message:

2017-10-24T19:57:08.0718472Z ##[error]Endpoint auth data not present: SystemVssConnection

**Comment by jabbera** [comment]
What agent version? What operating system is it running on?

**Comment by ricardoserradas** [comment]
Agent version: 1.95.3
OS: Windows Server 2012 R2 Datacenter

**Comment by jabbera** [comment]
Unfortunalty not. It is only supported on the xplat agent before version 2.
