### ISSUE TITLE
Replacement Pattern taken as tag

### ISSUE THREAD

**Issue by CouponsProjectHIT** [jabbera/vsts-git-release-tag#11]
Hi, I tried to create a tag like in the example you gave but the tag I got is V3.5.1, just like the replacement pattern.

My Release name is: Release-1.0.4.3-1
Search Regex: ([0-9]+.[0-9]+.[0-9]+.[0-9]+)-[0-9]+
Replacement Pattern: v3.5.1

What I missing here?

Thanks a lot.

**Comment by jabbera** [comment]
Hi. The RegEx has to match the whole string. I should really fix this. Try pretending your RegEx with: Release-

**Comment by CouponsProjectHIT** [comment]
OK I managed to get along with it, I have another question, is it possible to create a message with the tag?

**Comment by jabbera** [comment]
Sorry, this extension doesn’t currently support annotated tags. I look into is as a future feature request.
