### ISSUE TITLE
Support updating tags

### ISSUE THREAD

**Issue by galiana** [jabbera/vsts-git-release-tag#14]
Right now, I can't update an existing tag. 
This is useful when you have a tag per environment and you want to update to the commit deployed to that environment.
Currently, it is failing with:
Unable to create ref: refs/tags/kk UpdateStatus: 2 RepositoryId: [xxx] Commit: [xx]

Usualy this can be done removing and recreating the tag or using the --force parameter. I have checked that the service has the right to use --force.

**Comment by jabbera** [comment]
Good point! I’ll add this to the backlog.

**Comment by jabbera** [comment]
This is out in 3.0.1

**Comment by galiana** [comment]
Hi, I updated my release to 3.0.5 and used the new fields for static tags, but I still get:
2017-11-21T21:05:09.3425013Z ##[error]If you need to change permissions see: _admin/_versioncontrol?_a=security&repositoryId=xxxxxxxxxx
2017-11-21T21:05:09.3425013Z ##[error]Unable to create ref: tags/QA UpdateStatus: 6 RepositoryId: xxxxxxxxxxx Commit: xxxxxxxxxx

My project collection build services accounts are allowed to create tags and force push. Do I need anyting else?

**Comment by jabbera** [comment]
Hi. That’s a different error code. You were getting 2 before which was stale old red code. The vso source code is pretty explicit that 6 means lack of write permissions. Maybe try granting you build accounts admin and work your way backwards?

‘’’

     * The ref update request could not be completed because the user lacks write permissions required to write this ref
     */
    WritePermissionRequired = 6,
‘’’

**Comment by jabbera** [comment]
Also: vsts or on prem, if on perm which service pack?

**Comment by galiana** [comment]
It is VSTS. Thanks for the clarification, I was not aware of the meaning of the error

**Comment by galiana** [comment]
And yes, after adding contribute rights to the users... it's working, thanks!

**Comment by jabbera** [comment]
That’s great. I’ll add a comment to the error code! Thanks for letting me know what the issue was.
