### ISSUE TITLE
Versioning / require casing

### ISSUE THREAD

**Issue by dpmorrow** [jabbera/vsts-git-release-tag#17]
Hey, thanks for this I believe it will be useful.  I had an issue creating a PR for your as when I went to test my fix the extension version was 3.0.3 so my bump to 0.0.17 wasn't successful.

The issue is that the require for a couple of things is incorrectly capitalized.  Presumably it's been working fine on windows agents but will not work with the newer non-windows ones.

Here's a patch if that saves some time:

```
From 252fad60f09f5cc9ecdb0282b06788e962c0f8f0 Mon Sep 17 00:00:00 2001
From: Doug Morrow <douglas.p.morrow@gmail.com>
Date: Fri, 17 Nov 2017 15:45:25 -0800
Subject: [PATCH 1/1] fix interfaces path for non-windows agents

---
 Tasks/common/GitRefCreator.ts | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/Tasks/common/GitRefCreator.ts b/Tasks/common/GitRefCreator.ts
index d4e8811..e2d7c8c 100644
--- a/Tasks/common/GitRefCreator.ts
+++ b/Tasks/common/GitRefCreator.ts
@@ -1,8 +1,8 @@
 import * as vsts from "vso-node-api";
 import * as bld from "vso-node-api/BuildApi";
 import * as git from "vso-node-api/GitApi";
-import * as bldi from "vso-node-api/Interfaces/BuildInterfaces";
-import * as giti from "vso-node-api/Interfaces/GitInterfaces";
+import * as bldi from "vso-node-api/interfaces/BuildInterfaces";
+import * as giti from "vso-node-api/interfaces/GitInterfaces";
 import * as tl from "vsts-task-lib/task";
 import IArtifactData from "./IArtifactData";
 
-- 
2.13.5 (Apple Git-94)

```

**Comment by jabbera** [comment]
Thanks for this. I’ll merge Monday. I’ll also setup a Mac agent to run.

**Comment by dpmorrow** [comment]
Great, thanks!  I realized I forgot to compile the typescript *duh* and that was why I couldn't make a patched version work.  When I went to run the task though I was presented with an error that looks like npm install needed to be run on the build agent in the task's directory.  Not sure how that's supposed to work, but here's the error just in case it's not something stupid I'm doing when creating / installing the extension:

`Cannot find module 'vsts-task-lib/task'` in entry.js for the tag on release task in this case.

**Comment by jabbera** [comment]
I’ll sort it out. The release process in my vsts repo does the packaging. I wish Microsoft would let me open source a project hosted there.

**Comment by dpmorrow** [comment]
Oh!  That makes more sense now, yeah I was running into more stuff and that explains a lot!

If anything you'd probably have to make this an effective mirror of your VSTS repo.  I'll just stay tuned for your fix :).

Thanks again!

**Comment by jabbera** [comment]
This is all set in 3.0.5

**Comment by jabbera** [comment]
This is the authoritative source. VSTS pull this repo every commit and runs the build/release process. VSTS has build\release management tasks for manipulating and publishing visx (https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-developer-tools-build-tasks) 

Now that microsoft is support yaml builds (https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted.md) I'll be able to publish the build process at least. I'll switch once it's out of preview.
