### ISSUE TITLE
Feature Request: Support source code in GitHub

### ISSUE THREAD

**Issue by deadlydog** [jabbera/vsts-git-release-tag#19]
First off, thanks for this awesome extension :)

This extension works great for source code that I have in TFS Git, but it doesn't seem to be creating any tags for source control projects in GitHub. I have a TFS Build pulling the source code from GitHub and building the artifacts that get picked up by TFS Release Management. Am I doing something wrong, or is it just not supported at this time? Any plans to add that functionality in? I assume it would need GitHub credentials or an OAuth token or something? Also, I'm using on-prem TFS 2017 Update 2 if that makes a difference. Thanks!

**Comment by jabbera** [comment]
Hi, this uses the VSTS api so support for other git sources is not going to heppen unless msft extends the API.

**Comment by deadlydog** [comment]
Would it be possible to inspect the git repository URL and if `github.com` is present then use the GitHub API instead of the VSTS API? Is that something you would consider adding @jabbera?
