### ISSUE TITLE
Support replacement pattern for tag name

### ISSUE THREAD

**Issue by zivillian** [jabbera/vsts-git-release-tag#2]
We have multiple releases for multiple repositories, which have a product name prefix to distinguish the versions:

- ProductA 1.0.1
- ProductA 1.0.2
- ProductB 1.0.1
- ProductB 1.0.2

I would like to specify a Regex (or something similar) to define the tag name. Using a regex and replacement with captures it would be possible to create the tags `v1.0.1` and `v1.0.2` for both releases (instead of `ProductA 1.0.1`).

#### Example (.NET)
```
var pattern = @"Product A (\d\.\d\.\d)";
var replacement = "v$1";
var releasename = "Product A 1.0.1";
releasename = new Regex(pattern).Replace(releasename, replacement);
Console.WriteLine(releasename);
```

**Comment by jabbera** [comment]
This shouldn't be a problem. It's a holiday weekend in the states. I'll take a look Tuesday.

**Comment by jabbera** [comment]
This is all set in 1.0.3. https://github.com/jabbera/vsts-git-release-tag/commit/74bad69d12daf94f34cc823e531cb00458415c8d
