### ISSUE TITLE
Can install extension but does not appear in list of assignable extensions

### ISSUE THREAD

**Issue by RobertOwenJack** [jabbera/vsts-git-release-tag#34]
The extension seems to be exactly what I need. Unfortunately, after I install it, it does not not appear in the list of assignable tasks although in the list of market place extensions it is reported as installed. Not sure what to do ...

**Comment by jabbera** [comment]
vsts or on prem?

**Comment by RobertOwenJack** [comment]
vsts

**Comment by jabbera** [comment]
Sorry. I don't have an answer. I would expect it show up here in releases only. Maybe a support ticket?

![image](https://user-images.githubusercontent.com/301208/39771271-83ee447a-52bf-11e8-9982-00d5aac0a647.png)

**Comment by RobertOwenJack** [comment]
Thanks, a support ticket would be really helpful. I'm a bit puzzled as the extension has installed but just isn't visible as a usable task  from a release definition. Is there any information I could provide (are there any logs etc)?
________________________________

**Comment by jabbera** [comment]
I don’t have any ability to open a ticket on your account. You will need to open one. I think they are free although I never tried. (https://www.visualstudio.com/team-services/support/#vsts-support)

**Comment by RobertOwenJack** [comment]
Hi Mike

I opened some permissions for the release, uninstalled the extension and reinstalled it again. I found (by accident) the relevant tasks under tag artefacts and branch artefacts and have been able to successfully use the tagging task. I'm sure whether the permissions/uninstall/reinstall was the issue or whether it was I was looking for the wrong thing.  Thanks anyway - it is a really useful tool. I tried using one called Tag Release, which claims to Tag the build or release Colin's ALM Corner http://colinsalmcorner.com/post/new-task-tag-build-or-releasehttp://colinsalmcorner.com/post/new-task-tag-build-or-release but that didn't seem to do what I expected (it just set some tags in the VSTS build/release records and not the git source)

Not sure what I would have done without it.

Thanks again

Robert
________________________________
