### ISSUE TITLE
Unable to add task in release

### ISSUE THREAD

**Issue by danijam** [jabbera/vsts-git-release-tag#37]
![image](https://user-images.githubusercontent.com/40212250/41470517-b917ee74-70a8-11e8-94ab-0e9a31861924.png)

Extension is installed (I'm the admin) but when I go into a release and add a task it appears to be greyed out... Something I'm doing wrong?

**Comment by jabbera** [comment]
Hi,
It looks like you are still in the marketplace section. It should be listed in the top section as well. (Between add task and marketplace) Maybe do a force refresh?

**Comment by dviryo** [comment]
I see the same issue.
Is there a solution?

![image](https://user-images.githubusercontent.com/37534640/41906548-c3c10698-7946-11e8-933f-2034c87d2f31.png)

**Comment by jabbera** [comment]
Hi,

Did you try my comment above? Click the refresh button and then shift F5 to refresh the page?

I don’t have any control over that screen so if neither of those two things work you will need to submit an issue to msft as I cannot reproduce the issue.

**Comment by jabbera** [comment]
Oh. The extension is also just called tag. Remove git from the search window.

**Comment by dviryo** [comment]
Yes I tried, but still no success. 
I also assume it is vsts issue. I will check with them . 
Thanks!

**Comment by jabbera** [comment]
Did you try just using tag in the search box? The word git is not in the extension name?

**Comment by dviryo** [comment]
Yes. The issue isn't to find the extension. I can see it (not where I expect it to be) but I cannot use/install it

**Comment by jabbera** [comment]
Alright. Mind following up with the solution when you have it? 

Thanks!

**Comment by dwolan** [comment]
Hi @danijam,

It may not be the case but I also had a problem finding tasks from this extension. I made a mistake trying to find tasks from this extension using 'git' keyword. It took me a while to find it.

![image](https://user-images.githubusercontent.com/26650161/42329343-c0e1bb26-8070-11e8-934c-7db0843dd655.png)

![image](https://user-images.githubusercontent.com/26650161/42329385-db6ba236-8070-11e8-980b-872c8361cfad.png)

**Comment by danijam** [comment]
Hi @dwolan, Thanks, yes that is indeed the same for me.
