### ISSUE TITLE
Tag Artifacts always says  ##[warning]No TfsGit artifacts found although TfsGit artifacts are linked

### ISSUE THREAD

**Issue by Jazzman82** [jabbera/vsts-git-release-tag#4]
Here are the environment-infos:

...
[RELEASE_ARTIFACTS_KEYTECH_REPOSITORY_PROVIDER] --> [TfsGit]
...
[RELEASE_ARTIFACTS_FRAMEWORK_REPOSITORY_PROVIDER] --> [TfsGit]
...

**Comment by jabbera** [comment]
Please create a variable called:
system.debug
set the value to true

you should see much more descriptive text about why the artifacts are not being considered. If you still have questions please post the output of the task run.

**Comment by Jazzman82** [comment]
I have created the system.debug variable like you proposed but didn't see any additional output. 
I already saw some ##debug-lines in the tag artifacts log (tasklog_14).

What I noticed is that the system.debug turned into a system_debug with the dot replaced by an underscore (like the other variables also).

I attached the initialized and tag artifact logs. Thanks for your help.
[tasklog_14.txt](https://github.com/jabbera/vsts-git-release-tag/files/1073505/tasklog_14.txt)
[tasklog_1.txt](https://github.com/jabbera/vsts-git-release-tag/files/1073504/tasklog_1.txt)

**Comment by Jazzman82** [comment]
I just found the error! My agent was running on an older version. Updating it solved the issue. Thank you

**Comment by jabbera** [comment]
That's great news. What version did you upgrade to? I'll build a version check for the future.

**Comment by Jazzman82** [comment]
The new agent version is 2.112.0.
I believe the issue was caused by this bug:
