### ISSUE TITLE
Task appears as being installed but unable to use

### ISSUE THREAD

**Issue by RonKoppelaar** [jabbera/vsts-git-release-tag#40]
After installing the task in VSTS, it still appears within the marketplace steps when I want to add it.
However the button is grayed out, and show label "Installed".

When going on the extension manager (i'm project admin) it also shows up as begin installed.

**Comment by jabbera** [comment]
Sorry could you send a screenshot? Note: you cannot use the term git when searching for the task.

**Comment by RonKoppelaar** [comment]
[cid:image003.jpg@01D45058.385B2AF0]

This is  the task when I search for “Tag\ bran”. Its shows as being installed. But its within the group “Marketplace”. As I’m an admin on this project I know for sure its installed.
See also this screenshot’

[cid:image004.jpg@01D45058.385B2AF0]

Met vriendelijke groet,

Ron Koppelaar
Enterprise Architect

**Comment by jabbera** [comment]
Sorry, the screenshots didn't come through. I think it's because they were email attachments.

**Comment by jabbera** [comment]
There are 2 tasks. One called: Tag Artifacts and the other Branch Artifacts. Try just using the word tag or branch in the search box.
