### ISSUE TITLE
How do I add to release pipeline?

### ISSUE THREAD

**Issue by sheam** [jabbera/vsts-git-release-tag#42]
I installed the plugin, and I am admin/owner, but I can't seem to add this to the pipeline.
https://i.imgur.com/gFDcPz7.png

I see another _closed_ issue stating the exact same issue, but I don't see a solution in there.

**Comment by sheam** [comment]
It seems that the key is to uninstall, and then reinstall. I noticed that was the solution for someone else, and it worked for me too.

**Comment by jabbera** [comment]
It's really odd. There is nothing I can do to resolve this. It's totally on MSFT.
