### ISSUE TITLE
Is it possible to set multiple tags at once in the static options?

### ISSUE THREAD

**Issue by leomicheloni** [jabbera/vsts-git-release-tag#43]
Hi, 
 First at all I want to say thanks for this useful tool. I have the need to set more than one tag using the "static tag" options at once, is it possible. I'm willing to help to develop the feature is it is needed.
Thanks in advance!

**Comment by jabbera** [comment]
Hi! I would put N of the tasks in a row each with a single tag. I’m open to a PR but since I’m the one on the hook for maintenance it would be a complexity versus benefit call. Is there a reason N in a row won’t work?

**Comment by leomicheloni** [comment]
Didn't try it, I will. Thanks!

**Comment by leomicheloni** [comment]
BTW I can help you with maintenance if you will.
