### ISSUE TITLE
Is it possible to set variable in tag?

### ISSUE THREAD

**Issue by rerime** [jabbera/vsts-git-release-tag#48]
Hi, great extention!
Is it possible to set variable in tag like date?
Example, DEV-$(Get-Date -UFormat "%Y-%m-%d")

**Comment by jabbera** [comment]
I’m open to a PR with native support but this SO post shows a fairly easy way to do this yourself:
https://stackoverflow.com/questions/44738944/vsotfs-get-current-date-time-as-variable

**Comment by rerime** [comment]
Great, it works!
