### ISSUE TITLE
No TfsGit artifacts found [warning]

### ISSUE THREAD

**Issue by empitesithum** [jabbera/vsts-git-release-tag#49]
I get the warning: **No TfsGit artifacts found** and it never created tags on the git. Make this an Error rather marking it as a warning. Tags are important for my organization. 

This is my configuration:  
![pipeline](https://user-images.githubusercontent.com/11851588/54067151-85c4b480-4262-11e9-94ac-2507ce687092.png)  

My [tasklog_6.log](https://github.com/jabbera/vsts-git-release-tag/files/2948131/tasklog_6.log) log with `system.debug` set to `true`

**Comment by jabbera** [comment]
Your code is stored in Github, not azure devops. (From your log)

api.repository.provider=GitHub

This task only works with source code stored in azure devops. Microsoft needs to update their node api to support github before my task will.

**Comment by Rzpeg** [comment]
@jabbera 
We are having the same issue but with a Bitbucket Cloud hosted repository. 
Still no support from MS for different providers?

**Comment by aleksandra-nitka-epam** [comment]
Hello,

Same problem here ... Repo in BitBucket and we are using AzureDevOps - any solution how to tag branches if it's still not supported ? Or maybe it is now ?
