### ISSUE TITLE
Error message in CI/CD Pipeline: "unable to get local issuer certificate"

### ISSUE THREAD

**Issue by happyhippo69** [jabbera/vsts-git-release-tag#50]
Hi,
I have trouble using this task in our CI/CD Pipeline. We use "Tag Artifacts" and GIT with https.
What can I do solving this issue

**Comment by jabbera** [comment]
Please create a release varaiable called system.debug, set the value to true, re-run your release and post the log file from the task.

**Comment by happyhippo69** [comment]
[tasklog_14.log](https://github.com/jabbera/vsts-git-release-tag/files/2978157/tasklog_14.log)

**Comment by jabbera** [comment]
See the following comment. Your firm is using and internal CA and you need to tell Node to trust it:

https://github.com/jabbera/vsts-git-release-tag/issues/41#issuecomment-462492956
