### ISSUE TITLE
How to configure

### ISSUE THREAD

**Issue by 304NotModified** [jabbera/vsts-git-release-tag#53]
Hi! Thanks for this plugin!

Unfortantely we find it very difficult to configure.

![image](https://user-images.githubusercontent.com/5808377/60260559-25718580-98da-11e9-8bb6-d856b82c0bbe.png)

It's clear to create a fixed tag, just fill in "Static Tag name".

But how could we configure a tag like PROD-2019-06-27 (so current date with prefix PROD), or PROD-20190627-002 (release name with prefix PROD). What should we configure in Static, search and replacement? 

I've checked https://github.com/jabbera/vsts-git-release-tag/blob/master/overview.md, but also this isn't clear: 

> More complex you can specify a regex that MUST match the release name while including one or more capture groups.

Does that mean we should check the release name and create a regex to match that one?

**Comment by jabbera** [comment]
If you can get a variable set to what you want (TagValue for example) you should be able to set static tag to:: $(TagValue)

**Comment by fernanvarela** [comment]
What about using environment variables? I'm trying to do something like v.$(env:TagValue) or v.$env:TagValue and that is not working.

**Comment by jabbera** [comment]
I think azure pipelines will allow you to access any environment variable with  $(varname) if you replace _ with .. for example the environment variable SYSTEM_DEBUG should be accessible as $(System.Debug).

This isn’t really a feature of my tasks, just a feature of the platform.

**Comment by jmardones96** [comment]
¿Se puede agregar comentario al TAG aparte del nombre de la versión?
