### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dpgregory** [jabbera/vsts-git-release-tag#54]
I have this working fine on one of my pipelines and it's great! However on one of my other ones I am getting the below error. I have checked and double checked to see any differences between the pipelines, and just can't see why this one is failing. If you can shed any light on what I have missed, that would be great, thanks,

Starting: Tag Artifacts

==============================================================================

Task         : Tag Artifacts

Description  : Tag artifacts during release with ReleaseName.

Version      : 6.0.2

Author       : Michael Barry

Help         : 

==============================================================================

git-tag-on-release-task: Version: 6.0.2

(node:3148) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'replace' of undefined

Finishing: Tag Artifacts

**Comment by jabbera** [comment]
Can you set system.debug to true and rerun?

**Comment by dpgregory** [comment]
Thanks for taking the time to reply. Didn't think about doing the debug option, but here it is, not sure it's much help?:

##[debug]Evaluating condition for step: 'Tag Artifacts'

##[debug]Evaluating: succeeded()

##[debug]Evaluating succeeded:

##[debug]=> True

Author       : Michael Barry

Help         : 

==============================================================================

##[debug]agent.TempDirectory=D:\a\_temp

##[debug]loading inputs and endpoints

##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN

##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION

##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION

##[debug]loaded 3

##[debug]Agent.ProxyUrl=undefined

##[debug]Agent.CAInfo=undefined

##[debug]Agent.ClientCert=undefined

##[debug]Agent.SkipCertValidation=undefined

git-tag-on-release-task: Version: 6.0.2

##[debug]RELEASE_RELEASENAME=undefined

##[debug]staticTagName=null

##[debug]searchRegex=null

##[debug]regexFlags=null

##[debug]replacePattern=null

##[debug]Search Regex: '\s+', Replace Pattern: '', flags: 'g', staticTagName: ''

(node:7128) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'replace' of undefined

Finishing: Tag Artifacts

**Comment by jabbera** [comment]
RELEASE_RELEASENAME which is a predefined variable (https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch) is null. Are you using this task from a release?

**Comment by dpgregory** [comment]
No, it's from a pipeline, same as my other one which is working.

**Comment by dpgregory** [comment]
I just tried my other one, which I thought was working, in debug mode and turns out it isn't working either. However my repo is getting tagged with build version somehow! There isn't any other Task that I can that is doing it in the pipeline, or part of the Release....

**Comment by jabbera** [comment]
YAML pipeline? I’ve not tried that yet.

**Comment by dpgregory** [comment]
No not YAML, just a Build GUI one. Is this task only meant to work in releases, as apposed to build? I am using it in release pipeline and that one is working. That is the most important one, but like to have build numbers as well.

**Comment by jabbera** [comment]
It’s only build for releases. The functionally you want is built into azure pipelines for build: 

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#label-sources

**Comment by dpgregory** [comment]
Ah yes, I eventually found where that was now on the non-working pipeline and rectified! I wouldn't have found it without your help, so thanks a lot. And thanks for the task, makes branching a release so much easier!
