### ISSUE TITLE
No TfsGit artifacts found

### ISSUE THREAD

**Issue by greenmonster1** [jabbera/vsts-git-release-tag#61]
I am getting this warning on the release pipeline when I try to Tag. My Release Pipeline directly picks up the data from a Git repo on VSTS / ADO.

[Debug-Release.log](https://github.com/jabbera/vsts-git-release-tag/files/3892214/Debug-Release.log)

**Comment by jabbera** [comment]
Please upgrade to a current version and get back to me.

**Comment by greenmonster1** [comment]
That is where I started but scaled down after the error. Attached is the latest debug log.

[Debug-Release-v2.log](https://github.com/jabbera/vsts-git-release-tag/files/3892435/Debug-Release-v2.log)

**Comment by jabbera** [comment]
I’ll need to look more carefully into this. I looks for an artifact type specifically called: TfsGit. For some reason yours just say git. Can share your yaml configuration? (The subset related to artifact selection)

Matching variable:  release.artifacts.JAX-COS-FORMS.repository.provider, but artifact type: Git

**Comment by greenmonster1** [comment]
You know what I am already using this plugin in another pipeline and it works the only difference is I have a build and I do not download the code directly, I am going to go that route that will make things easier. Really appreciate your quick turn around.

**Comment by greenmonster1** [comment]
BTW, I will keep the issue open till I get it working possibly early next week since I am out rest of the then will close it on Wednesday.

**Comment by greenmonster1** [comment]
It worked with the build, thank you again, Happy Thanksgiving!!

**Comment by jabbera** [comment]
Glad to hear. I published version 8 which SHOULD sort the issue anyway.

**Comment by greenmonster1** [comment]
I went back and tried that too and it works (I mean the version 8), Really appreciate the quick turn around.
