### ISSUE TITLE
Does this tag in git or the artifact

### ISSUE THREAD

**Issue by lukaskolafa** [jabbera/vsts-git-release-tag#65]
Hello, I am quite confused from this Task. By name it looks like it would tag build artifacts, but it makes tags in git. From the description it was very hard to understand what is the intention. Or maybe does this task tag both git and artifact? could you please clarify? Thx.

**Comment by jabbera** [comment]
Hi,

Let say you build binaries from a commit. You then distribute those binaries from a Release pipeline. This task will tag the source code the binaries were built FROM with a tag during the release process (as opposed to the build process). The 2 most common use cases I know of are tagging or branching the source code when builds get to production or tagging the source with an environment name (DEV, UAT, PRD) when deployments get to a certain environment. Feel free to re-open if this doesn't answer your question.

**Comment by lukaskolafa** [comment]
Hi Mike,

 thank you so much for your answer. Now it is clear to me, your Task makes tags to git commits. 

 Not sure if this is possible, I would suggest a little rephrasing in the name of the task or at least in the description. As your Task is called `Tag Artifact`, it was quite misleading to me. Actually an 'Artifact' is a usual term used for DevOps Build Package (as well called Build Drops) - the result of the Build pipeline. And they can have tags too, which is very useful thing for release pipeline filtering.

but it is only a suggestion though..

**Comment by jabbera** [comment]
Thanks for the idea. I named the task before that product existed:-)
