### ISSUE TITLE
certificate has expired error (AddTrust)

### ISSUE THREAD

**Issue by marknitek** [jabbera/vsts-git-release-tag#68]
We have a OnPrem TFS and since the expiration of the AddTrust root certificate (https://superuser.com/questions/1556491/getting-ssl-certificate-error-on-valid-certificate-when-accessing-via-curl) this extension does not work anymore. We had similar issues with old build agents and resolved it by updating the agents to the newest version (which includes a new git.exe). I don't know what is causing the error in this extension. by looking at the source code it does not seem like its using the rest api for tagging? From my undestanding the AddTrust issue should only occour with old clients. 

We also removed the cert from our cert chain, cert check https://whatsmychaincert.com shows correct chain now, which is even more confusing.

**Comment by marknitek** [comment]
Ok and do you have an idea hiw to resolve it? Cert is removed from the chain and the build agent host. Build agent is up to date.

**Comment by jabbera** [comment]
Node has official documentation. See here for the environment variables you can set: https://github.com/jabbera/vsts-git-release-tag/issues/41#issuecomment-462492956
