### ISSUE TITLE
Tag name Chnage.

### ISSUE THREAD

**Issue by sunilbindra** [jabbera/vsts-git-release-tag#7]
Can I change the tag name. if I want to include some words like  {ProjectName}{BuildNumber}{releaseName}

**Comment by jabbera** [comment]
Not currently. You would need to make the release name include all the information. My releases typically only have a single artifact so I put the build number in the release name. What do you mean by ProjectName? Team project name? 

I’m open to adding the feature once I understand the ask.

**Comment by sunilbindra** [comment]
Yes Team Project Name. Actually I want to customize the tag name, if there is any possibility. What is regex is used for. Any example please

**Comment by sunilbindra** [comment]
I am just trying using the team project name. but my requirement is to use any thing like {AnyString} - {BuildNumber} - {Iteration}

AnyString and  Iteration will be a variable.

**Comment by jabbera** [comment]
Sorry for the delay. The way I've coded this to be used is:

My Release Name is:   Core Release-$(Build.BuildNumber)-$(rev:r)
An Example: Core Release 3.0.17270.8-1

I want my source tag (or branch) to be: v3.0.17270.8
My Regex is:

Core Release-([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)-[0-9]+

The replacement pattern (incorrectly labeled sample string) is: v$1
Which translated to: prepend the letter 'v' to the first capture group.

Does this help?
