### ISSUE TITLE
`Unable to create ref: tags/***`

### ISSUE THREAD

**Issue by Saibamen** [jabbera/vsts-git-release-tag#83]
Few weeks ago, this works OK

Now I have this error:

```
If you need to change permissions see: _admin/_versioncontrol?_a=security&repositoryId=ZZZ
[error]Unable to create ref: tags/my_dev UpdateStatus: 1 RepositoryId: ZZZ Old Commit: XXX New Commit: YYY
```

**Comment by Saibamen** [comment]
OK, few minutes ago I fixed this by adding permissions to `Security Service Group`:

1. Create tag
2. Force push
3. Read

Please add required permissions to error message

**Comment by thomaskennedy1066** [comment]
Thank you!  Spent too long trying to figure this out.  This worked for me

**Comment by Saibamen** [comment]
PR: https://github.com/jabbera/vsts-git-release-tag/pull/84

**Comment by drewwilliams1982** [comment]
These extra perms worked for me! To aid anyone else, set the above permissions by navigating to:
Project Settings > Repositories > All Repositories > Security
