### ISSUE TITLE
Unable to GIT Tag from YAML pipeline without GIT checkout

### ISSUE THREAD

**Issue by davidsekar** [jabbera/vsts-git-release-tag#89]
In my case, the build happens in a separate YAML pipeline (XXX) and artifacts are created.

The created artifacts are then used in another YAML pipeline as Pipeline resource reference as shown below
```
 pipelines:
    - pipeline: XXXBuild # Name of the pipeline resource
      source: XXXX # Name of the triggering pipeline
```

Now when I use tag on release it is unable to tag and results in error.
`- task: git-tag-on-release-task@9
   inputs:
     searchRegex: '([0-9]+.[0-9]+.[0-9]+.[0-9]+)'
     replacePattern: 'v$1'
`

Error
`##[error]Unable to create ref: tags/v3.5.5.257 WEB RELEASE UpdateStatus: 3 RepositoryId: YYYYYY Old Commit: 0000000000000000000000000000000000000000 New Commit: 63e4c513e6749e329e7e63d434d2f72d10b458e9`

I have verified that the build collection service has all required permissions. Not sure if this task supports this use-case.

Kindly help

**Comment by jabbera** [comment]
If you are using yaml pipelines this task is mostly added complexity. I tend to just use a script task with git commands.

**Comment by davidsekar** [comment]
Thanks @jabbera for your quick response.

Between your task was very useful for Non-Yaml based Azure pipelines and have used it in multiple pipelines. Thanks for your contributions
