### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by rifaterdemsahin** [jabbera/vsts-git-release-tag#9]
We need documentation about how to use it.

**Comment by jabbera** [comment]
I can create some documentation but it’s really just, drop the task into your release pipeline. It will create branches with your release name for all TfsGit artifacts. What specific problem are you having?

**Comment by rifaterdemsahin** [comment]
Error

If you need to change permissions see: _admin/_versioncontrol?_a=security&repositoryId=391b8215-c148-465a-bdbf-418e656c724aUnable to create ref: refs/heads/dev/Release-26 UpdateStatus: 3 RepositoryId: 391b8215-c148-465a-bdbf-418e656c724a Commit: 27a9105ff7baf4bffc65e42609e96852ae43ef6c | If you need to change permissions see: _admin/_versioncontrol?_a=security&repositoryId=391b8215-c148-465a-bdbf-418e656c724a |   | Unable to create ref: refs/heads/dev/Release-26 UpdateStatus: 3 RepositoryId: 391b8215-c148-465a-bdbf-418e656c724a Commit: 27a9105ff7baf4bffc65e42609e96852ae43ef6c
-- | -- | -- | --
If you need to change permissions see: _admin/_versioncontrol?_a=security&repositoryId=391b8215-c148-465a-bdbf-c724a
  | Unable to create ref: refs/heads/dev/Release-26 UpdateStatus: 3 RepositoryId: 391b8215-c148-465a-bdbf-424a Commit: 27a9105ff7baf4bffe96852ae43ef6c
 



**ACCESS CONTROL SUMMARY**
Shows information about the permissions being granted to this identity
Contribute	Allow
Create branch	Allow
Create repository	Allow
Create tag	Allow
Delete repository	Allow
Edit policies	Allow
Exempt from policy enforcement	Allow
Force push (rewrite history, delete branches and tags)	Allow
Manage notes	Allow
Manage permissions	Allow
Read	Allow
Remove others' locks	Allow
Rename repository	Allow

**Comment by jabbera** [comment]
Can you post your entire log file with system.debug set to true? Is this on prem or vsts?

**Comment by rifaterdemsahin** [comment]
after cleaning up the settings. it started working.

please have a documentation about what do there settings do ???

- Branch folder
- search regex
- regex flags
- sample string

**Comment by jabbera** [comment]
Documentation updated. Will publish to marketplace soon. Note: Sample String is mislabeled. It should be called Replacement String which is fixed in the version I'm going to push. Feel free to re-open if you have more questions.

https://github.com/jabbera/vsts-git-release-tag/blob/master/overview.md
